// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using WashPoints.Infrastructure.Persistencia;

#nullable disable

namespace WashPoints.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(WashPointsDbContext))]
    partial class WashPointsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WashPoints.Domain.Catalogo.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("WashPoints.Domain.Catalogo.Lavadero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("lavaderos", (string)null);
                });

            modelBuilder.Entity("WashPoints.Domain.Catalogo.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("LavaderoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lavadero_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("LavaderoId", "Nombre")
                        .IsUnique();

                    b.ToTable("puestos", (string)null);
                });

            modelBuilder.Entity("WashPoints.Domain.Catalogo.TipoLavado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<Guid>("LavaderoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lavadero_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioSena")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_sena");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_total");

                    b.HasKey("Id");

                    b.HasIndex("LavaderoId", "Nombre")
                        .IsUnique();

                    b.ToTable("tipos_lavado", (string)null);
                });

            modelBuilder.Entity("WashPoints.Domain.Turnos.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CerradoEn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cerrado_en");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("ConfirmadoEn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("LavaderoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lavadero_id");

                    b.Property<string>("MpPreferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mp_preference_id");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origen");

                    b.Property<decimal>("PrecioSena")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_sena");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("uuid")
                        .HasColumnName("puesto_id");

                    b.Property<NpgsqlRange<DateTime>>("Rango")
                        .HasColumnType("tsrange")
                        .HasColumnName("rango");

                    b.Property<Guid>("TipoLavadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_lavado_id");

                    b.HasKey("Id");

                    b.HasIndex("PuestoId");

                    b.HasIndex("TipoLavadoId");

                    b.HasIndex("LavaderoId", "Estado");

                    b.ToTable("turnos", (string)null);
                });

            modelBuilder.Entity("WashPoints.Domain.Turnos.Turno", b =>
                {
                    b.HasOne("WashPoints.Domain.Catalogo.Puesto", null)
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WashPoints.Domain.Catalogo.TipoLavado", null)
                        .WithMany()
                        .HasForeignKey("TipoLavadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
